spring.application.name=WhatToEat
spring.profiles.active=dev
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.metrics.tags.application=WhatToEat
