spring.application.name=WhatToEat
spring.profiles.active=dev
app.version=${APP_VERSION:1.0.0}
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.metrics.tags.application=WhatToEat
management.metrics.distribution.percentiles-histogram.http.server.requests=true
